
-------------------------------------------------------------------------------------
--------------- /* DATOS ABIERTOS ANALISIS DE DATOS EN SQL */ -----------------------
-------------------------------------------------------------------------------------


-- NUMERO DE HABITANTES A LA ULTIMA FECHA DE LA DATA / POBLACION POR DEPARTAMENTO

SELECT SUM(POBLACION) POBLACION_TOTAL FROM 
(SELECT DEPARTAMENTO, MAX(POBLACION_DEPARTAMENTO) POBLACION
		FROM DAPROJECT
		GROUP BY DEPARTAMENTO) A;

SELECT DEPARTAMENTO, MAX(POBLACION_DEPARTAMENTO) POBLACION
		FROM DAPROJECT
		GROUP BY DEPARTAMENTO;

-- CANTIDAD DE CONEXIONES POR TECNOLOGIAS 

SELECT PERIODO,TECNOLOGÍA , SUM(CANT_CONEXIONES) CONEXIONES_TOTALES
	   FROM DAPROJECT
	   GROUP BY PERIODO,TECNOLOGÍA
	   ORDER BY PERIODO, SUM(CANT_CONEXIONES) DESC;

-- CANTIDAD DE CONEXIONES POR EMPRESA / TOTAL DE CONEXIONES

SELECT EMPRESA, SUM(CANT_CONEXIONES) CONEXIONES_TOTALES
		FROM DAPROJECT
		GROUP BY EMPRESA ORDER BY SUM(CANT_CONEXIONES) DESC;

SELECT SUM(CONEXIONES_TOTALES) CONEXIONES_TOTALES FROM (
SELECT EMPRESA, SUM(CANT_CONEXIONES) CONEXIONES_TOTALES
		FROM DAPROJECT
		GROUP BY EMPRESA-- ORDER BY SUM(CANT_CONEXIONES) DESC
		) A;
	
-- CREAMOS UN NUEVO CAMPO (REGION)

ALTER TABLE DAPROJECT
ADD REGION NVARCHAR(50);

UPDATE DAPROJECT
SET REGION = 
    CASE 
        WHEN DEPARTAMENTO = 'PIURA' THEN 'COSTA'
        WHEN DEPARTAMENTO = 'AMAZONAS' THEN 'SELVA'
        WHEN DEPARTAMENTO = 'LIMA' THEN 'COSTA'
        WHEN DEPARTAMENTO = 'AYACUCHO' THEN 'SIERRA'
        WHEN DEPARTAMENTO = 'CALLAO' THEN 'COSTA'
        WHEN DEPARTAMENTO = 'AREQUIPA' THEN 'SIERRA'
        WHEN DEPARTAMENTO = 'LA LIBERTAD' THEN 'COSTA'
        WHEN DEPARTAMENTO = 'MADRE DE DIOS' THEN 'SELVA'
        WHEN DEPARTAMENTO = 'TACNA' THEN 'COSTA'
        WHEN DEPARTAMENTO = 'APURIMAC' THEN 'SIERRA'
        WHEN DEPARTAMENTO = 'PASCO' THEN 'SIERRA'
        WHEN DEPARTAMENTO = 'HUANCAVELICA' THEN 'SIERRA'
        WHEN DEPARTAMENTO = 'SAN MARTIN' THEN 'SELVA'
        WHEN DEPARTAMENTO = 'LORETO' THEN 'SELVA'
        WHEN DEPARTAMENTO = 'LAMBAYEQUE' THEN 'COSTA'
        WHEN DEPARTAMENTO = 'TUMBES' THEN 'COSTA'
        WHEN DEPARTAMENTO = 'ANCASH' THEN 'SIERRA'
        WHEN DEPARTAMENTO = 'CUSCO' THEN 'SIERRA'
        WHEN DEPARTAMENTO = 'UCAYALI' THEN 'SELVA'
        WHEN DEPARTAMENTO = 'CAJAMARCA' THEN 'SIERRA'
        WHEN DEPARTAMENTO = 'MOQUEGUA' THEN 'COSTA'
        WHEN DEPARTAMENTO = 'HUANUCO' THEN 'SIERRA'
        WHEN DEPARTAMENTO = 'ICA' THEN 'COSTA'
        WHEN DEPARTAMENTO = 'JUNIN' THEN 'SIERRA'
        WHEN DEPARTAMENTO = 'PUNO' THEN 'SIERRA'
        ELSE 'DESCONOCIDO'
    END;


SELECT DISTINCT REGION FROM DAPROJECT;

-- CANTIDAD DE CONEXIONES POR REGION 

SELECT REGION, SUM(CANT_CONEXIONES) CONEXIONES_TOTALES
		FROM DAPROJECT
		GROUP BY REGION ORDER BY SUM(CANT_CONEXIONES) DESC;


-- AGREGAMOS EL CAMPO VELOCIDAD EN MBPS

UPDATE DAPROJECT
SET VELOC_INFERIOR_KBPS = '0'
WHERE VELOC_INFERIOR_KBPS = 'N.A.'; -- REMPLAZAMOS LOS N.A POR EL VALOR 0

ALTER TABLE DAPROJECT 
ALTER COLUMN VELOC_INFERIOR_KBPS FLOAT; -- CONVERTIMOS A FLOAT EL CAMPO

-- NUEVO CAMPO EN MBPS PARA VEL_INF

ALTER TABLE DAPROJECT
ADD VEL_INF_MBPS FLOAT; 

UPDATE DAPROJECT
SET VEL_INF_MBPS = 
    CASE WHEN VELOC_INFERIOR_KBPS = '0' THEN 0.25
		ELSE VELOC_INFERIOR_KBPS/1024
		 END;

-- NUEVO CAMPO EN MBPS PARA VEL_SUP

UPDATE DAPROJECT
SET VELOC_SUPERIOR_EXCLUYENTE_KBPS = '0'
WHERE VELOC_SUPERIOR_EXCLUYENTE_KBPS = 'N.A.';

ALTER TABLE DAPROJECT 
ALTER COLUMN VELOC_SUPERIOR_EXCLUYENTE_KBPS FLOAT;

ALTER TABLE DAPROJECT
ADD VEL_SUP_MBPS FLOAT; 

UPDATE DAPROJECT
SET VEL_SUP_MBPS = 
    CASE WHEN VELOC_SUPERIOR_EXCLUYENTE_KBPS = '0' THEN 0.25
		ELSE VELOC_SUPERIOR_EXCLUYENTE_KBPS/1024
		 END;


-- VELOCIDAD PROMEDIO INFERIOR Y SUPERIOR EN MBPS POR REGION , DEPARTAMENTO Y DISTRITO

SELECT REGION,ROUND(AVG(VEL_INF_MBPS),2) VELPROM_INF_MBPS, ROUND(AVG(VEL_SUP_MBPS),2) VELPROM_SUP_MBPS
	FROM DAPROJECT
	GROUP BY REGION;


SELECT REGION,DEPARTAMENTO , ROUND(AVG(VEL_INF_MBPS),2) VELPROM_INF_MBPS,ROUND(AVG(VEL_SUP_MBPS),2) VELPROM_SUP_MBPS
	FROM DAPROJECT
	GROUP BY REGION,DEPARTAMENTO
	ORDER BY REGION, AVG(VEL_INF_MBPS) DESC;


-- VELOCIDAD PROMEDIO INFERIOR Y SUPERIOR (MBPS) EN LOS DISTRITOS DE LIMA

SELECT DEPARTAMENTO,DISTRITO,ROUND(AVG(VEL_INF_MBPS),2) VELPROM_INF_MBPS, ROUND(AVG(VEL_SUP_MBPS),2) VELPROM_SUP_MBPS
	FROM DAPROJECT
	WHERE DEPARTAMENTO = 'LIMA'
	GROUP BY DEPARTAMENTO,DISTRITO
	ORDER BY DEPARTAMENTO, AVG(VEL_SUP_MBPS) DESC;


-- SELECT * FROM DAPROJECT

-- 